### ISSUE TITLE
Make search in history possible

### ISSUE THREAD

**Issue by RGUSolita** [Julius-Bendt/tid.jub.dk#39]
Feature to enable search through the logs for fx. a ticket number.

**Comment by Julius-Bendt** [comment]
I've almost finished the feature. I just have some refactorings to do.

Search results will appear when you search, otherwise the day-select will be shown.
I have no idea about performance though 

![image](https://github.com/Julius-Bendt/tid.jub.dk/assets/22844949/626c8a8a-a7c4-4448-a1d2-84fd4595b7d5)
